# Generated by Django 4.1.2 on 2023-01-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='voiceRegisterMaxNote',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='voiceRegisterMinNote',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
