# Generated by Django 4.1.2 on 2023-01-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user_backend', '0002_alter_user_voiceregistermaxnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='voiceRegisterMaxNote',
            new_name='voiceRangeMaxNote',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='voiceRegisterMinNote',
            new_name='voiceRangeMinNote',
        ),
    ]
